export const chips = [
    { name: 'all', titleVi: 'Tất cả', link: '', opened: true },
    { name: 'music', titleVi: 'Âm nhạc', link: '', opened: false },
    { name: 'news', titleVi: 'Tin tức', link: '', opened: false },
    {
        name: 'combination',
        titleVi: 'Danh sách kết hợp',
        link: '',
        opened: false,
    },
    { name: 'live', titleVi: 'Trực tiếp', link: '', opened: false },
    { name: 'game', titleVi: 'Trò chơi', link: ', opened: false ' },
    { name: 'cartoon', titleVi: 'Hoạt họa', link: '', opened: false },
    {
        name: 'situationComedy',
        titleVi: 'Hài kịch tình huống',
        link: '',
        opened: false,
    },
    {
        name: 'actionAdventureGame',
        titleVi: 'Trò chơi hành động phiêu lưu',
        link: '',
        opened: false,
    },
    { name: 'pet', titleVi: 'Thú cưng', link: '', opened: false },
    { name: 'foodball', titleVi: 'Bóng đá', link: '', opened: false },
    {
        name: 'recentlyUpload',
        titleVi: 'Mới tải lên gần đây',
        link: '',
        opened: false,
    },
    { name: 'watched', titleVi: 'Đã xem', link: '', opened: false },
    { name: 'post', titleVi: 'Bài đăng', link: '', opened: false },
    { name: 'newProposal', titleVi: 'Đề xuất mới', link: '', opened: false },
];
